=== aquasecurity/cloud-metadata/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "apiVersion": {
            "type": "integer"
        },
        "version": {
            "type": "integer"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "description_file_path": {
            "type": "string"
        },
        "custom": {
            "type": "object",
            "properties": {
                "severity": {
                    "type": "string"
                },
                "possibleImpact": {
                    "type": "string"
                },
                "remediations": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string"
                                },
                                "remediation_path": {
                                    "type": "string"
                                },
                                "remediation_type": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "title",
                                "remediation_path",
                                "remediation_type"
                            ]
                        }
                    ]
                },
                "references": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "title",
                                "url"
                            ]
                        }
                    ]
                },
                "externalToolIds": {
                    "type": "object",
                    "properties": {
                        "cfsec": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "cspm": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "integer"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "name"
                                    ]
                                }
                            ]
                        },
                        "tfsec": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    }
                }
            },
            "required": [
                "severity",
                "possibleImpact",
                "references",
                "externalToolIds"
            ]
        }
    },
    "required": [
        "id",
        "apiVersion",
        "version",
        "title",
        "description",
        "custom"
    ]
}

=== aquasecurity/cloud-metadata/google/gke/metadata-endpoints-disabled/metadata.json
{
    "id": "AVD-GCP-0031",
    "apiVersion": 2,
    "version": 1,
    "title": "Legacy metadata endpoints enabled.",
    "description": "The Compute Engine instance metadata server exposes legacy v0.1 and v1beta1 endpoints, which do not enforce metadata query headers. \n\nThis is a feature in the v1 APIs that makes it more difficult for a potential attacker to retrieve instance metadata. \n\nUnless specifically required, we recommend you disable these legacy APIs.\n\nWhen setting the metadata block, the default value for disable-legacy-endpoints is set to true, they should not be explicitly enabled.",
    "custom": {
        "severity": "HIGH",
        "possibleImpact": "Legacy metadata endpoints don't require metadata headers",
        "references": [
            {
                "title": "Hardening your cluster's security",
                "url": "https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster#protect_node_metadata_default_for_112"
            }
        ],
        "externalToolIds": {
            "cfsec": [],
            "cspm": [],
            "tfsec": [
                "google-gke-metadata-endpoints-disabled"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/aws/elastic-search/encrypt-replication-group/metadata.json
{
    "id": "AVD-AWS-0045",
    "apiVersion": 2,
    "version": 1,
    "title": "Unencrypted Elasticache Replication Group.",
    "description": "You should ensure your Elasticache data is encrypted at rest to help prevent sensitive information from being read by unauthorised users.",
    "custom": {
        "severity": "HIGH",
        "possibleImpact": "Data in the replication group could be readable if compromised",
        "references": [
            {
                "title": "At-Rest Encryption in ElastiCache for Redis",
                "url": "https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/at-rest-encryption.html"
            }
        ],
        "externalToolIds": {
            "cfsec": [
                "aws-elastic-search-encrypt-replication-group"
            ],
            "cspm": [],
            "tfsec": [
                "aws-elastic-search-encrypt-replication-group"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/aws/vpc/disallow-mixed-sgr/metadata.json
{
  "id": "AVD-AWS-0100",
  "apiVersion": 2,
  "version": 1,
  "title": "Ensures that usage of security groups with inline rules and security group rule resources are not mixed.",
  "description": "Mixing Terraform standalone security_group_rule resource and security_group resource with inline ingress/egress rules results in rules being overwritten during Terraform apply.",
  "custom": {
    "severity": "LOW",
    "possibleImpact": "Security group rules will be overwritten and will result in unintended blocking of network traffic",
    "references": [],
    "externalToolIds": {
      "cfsec": [
        "aws-vpc-disallow-mixed-sgr"
      ],
      "cspm": [
        {
          "id": -1,
          "name": "TODO-CSPM-PLUGIN-NAME"
        }
      ],
      "tfsec": [
        "aws-vpc-disallow-mixed-sgr"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/aws/launch/no-sensitive-info/metadata.json
{
  "id": "AVD-AWS-0068",
  "apiVersion": 2,
  "version": 1,
  "title": "Ensure all data stored in the Launch configuration EBS is securely encrypted",
  "description": "When creating Launch Configurations, user data can be used for the initial configuration of the instance. User data must not contain any sensitive data.",
  "custom": {
    "severity": "HIGH",
    "possibleImpact": "Sensitive credentials in user data can be leaked",
    "references": [],
    "externalToolIds": {
      "cfsec": [
        "aws-launch-no-sensitive-info"
      ],
      "cspm": [],
      "tfsec": [
        "aws-launch-no-sensitive-info"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/azure/storage/use-secure-tls-policy/metadata.json
{
    "id": "AVD-AZU-0052",
    "apiVersion": 2,
    "version": 1,
    "title": "The minimum TLS version for Storage Accounts should be TLS1_2",
    "description": "Azure Storage currently supports three versions of the TLS protocol: 1.0, 1.1, and 1.2. \n\nAzure Storage uses TLS 1.2 on public HTTPS endpoints, but TLS 1.0 and TLS 1.1 are still supported for backward compatibility.\n\nThis check will warn if the minimum TLS is not set to TLS1_2.",
    "custom": {
        "severity": "CRITICAL",
        "possibleImpact": "The TLS version being outdated and has known vulnerabilities",
        "references": [
            {
                "title": "Enforce a minimum required version of Transport Layer Security (TLS) for incoming requests",
                "url": "https://docs.microsoft.com/en-us/azure/storage/common/transport-layer-security-configure-minimum-version"
            }
        ],
        "externalToolIds": {
            "cfsec": [],
            "cspm": [],
            "tfsec": [
                "azure-storage-use-secure-tls-policy"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/google/sql/enable-pg-temp-file-logging/metadata.json
{
  "id": "AVD-GCP-0052",
  "apiVersion": 2,
  "version": 1,
  "title": "Temporary file logging should be enabled for all temporary files.",
  "description": "Temporary files are not logged by default. To log all temporary files, a value of `0` should set in the `log_temp_files` flag - as all files greater in size than the number of bytes set in this flag will be logged.",
  "custom": {
    "severity": "MEDIUM",
    "possibleImpact": "Use of temporary files will not be logged",
    "references": [
      {
        "title": "title",
        "url": "https://postgresqlco.nf/doc/en/param/log_temp_files/"
      }
    ],
    "externalToolIds": {
      "cfsec": [],
      "cspm": [],
      "tfsec": [
        "google-sql-enable-pg-temp-file-logging"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/azure/datalake/enable-at-rest-encryption/metadata.json
{
    "id": "AVD-AZU-0026",
    "apiVersion": 2,
    "version": 1,
    "title": "Unencrypted data lake storage.",
    "description": "Datalake storage encryption defaults to Enabled, it shouldn't be overridden to Disabled.",
    "custom": {
        "severity": "HIGH",
        "possibleImpact": "Data could be read if compromised",
        "references": [
            {
                "title": "Overview of security in Azure Data Lake Storage Gen1",
                "url": "https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-security-overview"
            }
        ],
        "externalToolIds": {
            "cfsec": [],
            "cspm": [],
            "tfsec": [
                "azure-datalake-enable-at-rest-encryption"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/aws/rds/encrypt-cluster-storage-data/metadata.json
{
  "id": "AVD-AWS-0079",
  "apiVersion": 2,
  "version": 1,
  "title": "There is no encryption specified or encryption is disabled on the RDS Cluster.",
  "description": "Encryption should be enabled for an RDS Aurora cluster. \n\nWhen enabling encryption by setting the kms_key_id, the storage_encrypted must also be set to true.",
  "custom": {
    "severity": "HIGH",
    "possibleImpact": "Data can be read from the RDS cluster if it is compromised",
    "references": [
      {
        "title": "title",
        "url": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html"
      }
    ],
    "externalToolIds": {
      "cfsec": [
        "aws-rds-encrypt-cluster-storage-data"
      ],
      "cspm": [
        {
          "id": 237,
          "name": "rds/rdsEncryptionEnabled"
        }
      ],
      "tfsec": [
        "aws-rds-encrypt-cluster-storage-data"
      ]
    }
  }
}
