=== aquasecurity/cloud-metadata/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "apiVersion": {
            "type": "integer"
        },
        "version": {
            "type": "integer"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "description_file_path": {
            "type": "string"
        },
        "custom": {
            "type": "object",
            "properties": {
                "severity": {
                    "type": "string"
                },
                "possibleImpact": {
                    "type": "string"
                },
                "remediations": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string"
                                },
                                "remediation_path": {
                                    "type": "string"
                                },
                                "remediation_type": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "title",
                                "remediation_path",
                                "remediation_type"
                            ]
                        }
                    ]
                },
                "references": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "title",
                                "url"
                            ]
                        }
                    ]
                },
                "externalToolIds": {
                    "type": "object",
                    "properties": {
                        "cfsec": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "cspm": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "integer"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "name"
                                    ]
                                }
                            ]
                        },
                        "tfsec": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    }
                }
            },
            "required": [
                "severity",
                "possibleImpact",
                "references",
                "externalToolIds"
            ]
        }
    },
    "required": [
        "id",
        "apiVersion",
        "version",
        "title",
        "description",
        "custom"
    ]
}

=== aquasecurity/cloud-metadata/google/gke/node-metadata-security/metadata.json
{
  "id": "AVD-GCP-0035",
  "apiVersion": 2,
  "version": 1,
  "title": "Node metadata value disables metadata concealment.",
  "description": "If the workload_metadata_config block within node_config is included, the node_metadata attribute should be configured securely.\n\nThe attribute should be set to SECURE to use metadata concealment, or GKE_METADATA_SERVER if workload identity is enabled. This ensures that the VM metadata is not unnecessarily exposed to pods.",
  "custom": {
    "severity": "HIGH",
    "possibleImpact": "Metadata that isn't concealed potentially risks leakage of sensitive data",
    "references": [
      {
        "title": "title",
        "url": "https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata#create-concealed"
      }
    ],
    "externalToolIds": {
      "cfsec": [],
      "cspm": [],
      "tfsec": [
        "google-gke-node-metadata-security"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/azure/container/limit-authorized-ips/metadata.json
{
    "id": "AVD-AZU-0013",
    "apiVersion": 2,
    "version": 1,
    "title": "Ensure AKS has an API Server Authorized IP Ranges enabled",
    "description": "The API server is the central way to interact with and manage a cluster. To improve cluster security and minimize attacks, the API server should only be accessible from a limited set of IP address ranges.",
    "custom": {
        "severity": "CRITICAL",
        "possibleImpact": "Any IP can interact with the API server",
        "references": [
            {
                "title": "API server authorized IP ranges in Azure Kubernetes Service (AKS)",
                "url": "https://docs.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges"
            }
        ],
        "externalToolIds": {
            "cfsec": [],
            "cspm": [],
            "tfsec": [
                "azure-container-limit-authorized-ips"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/google/sql/mysql-no-local-infile/metadata.json
{
  "id": "AVD-GCP-0054",
  "apiVersion": 2,
  "version": 1,
  "title": "Disable local_infile setting in MySQL",
  "description": "Arbitrary files can be read from the system using LOAD_DATA unless this setting is disabled.",
  "custom": {
    "severity": "HIGH",
    "possibleImpact": "Arbitrary files read by attackers when combined with a SQL injection vulnerability.",
    "references": [
      {
        "title": "title",
        "url": "https://dev.mysql.com/doc/refman/8.0/en/load-data-local-security.html"
      }
    ],
    "externalToolIds": {
      "cfsec": [],
      "cspm": [
        {
          "id": -1,
          "name": "TODO-CSPM-PLUGIN-NAME"
        }
      ],
      "tfsec": [
        "google-sql-mysql-no-local-infile"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/aws/ecr/no-public-access/metadata.json
{
  "id": "AVD-AWS-0032",
  "apiVersion": 2,
  "version": 1,
  "title": "ECR repository policy must block public access",
  "description": "Allowing public access to the ECR repository risks leaking sensitive of abusable information",
  "custom": {
    "severity": "HIGH",
    "possibleImpact": "Risk of potential data leakage of sensitive artifacts",
    "references": [],
    "externalToolIds": {
      "cfsec": [
        "aws-ecr-no-public-access"
      ],
      "cspm": [
        {
          "id": -1,
          "name": "TODO-CSPM-PLUGIN-NAME"
        }
      ],
      "tfsec": [
        "aws-ecr-no-public-access"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/aws/ecs/enable-container-insight/metadata.json
{
  "id": "AVD-AWS-0034",
  "apiVersion": 2,
  "version": 1,
  "title": "ECS clusters should have container insights enabled",
  "description": "Cloudwatch Container Insights provide more metrics and logs for container based applications and micro services.",
  "custom": {
    "severity": "LOW",
    "possibleImpact": "Not all metrics and logs may be gathered for containers when Container Insights isn't enabled",
    "references": [
      {
        "title": "title",
        "url": "https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights.html"
      }
    ],
    "externalToolIds": {
      "cfsec": [
        "aws-ecs-enable-container-insight"
      ],
      "cspm": [
        {
          "id": -1,
          "name": "TODO-CSPM-PLUGIN-NAME"
        }
      ],
      "tfsec": [
        "aws-ecs-enable-container-insight"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/azure/database/postgres-configuration-log-checkpoints/metadata.json
{
    "id": "AVD-AZU-0020",
    "apiVersion": 2,
    "version": 1,
    "title": "Ensure server parameter 'log_checkpoints' is set to 'ON' for PostgreSQL Database Server",
    "description": "Postgresql can generate logs for checkpoints to improve visibility for audit and configuration issue resolution.",
    "custom": {
        "severity": "MEDIUM",
        "possibleImpact": "No error and query logs generated on checkpoint",
        "references": [
            {
                "title": "Logs",
                "url": "https://docs.microsoft.com/en-us/azure/postgresql/concepts-server-logs#configure-logging"
            }
        ],
        "externalToolIds": {
            "cfsec": [],
            "cspm": [
                {
                    "id": 622,
                    "name": "postgresqlserver/logCheckpointsEnabled"
                }
            ],
            "tfsec": [
                "azure-database-postgres-configuration-log-checkpoints"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/google/iam/no-project-level-service-account-impersonation/metadata.json
{
  "id": "AVD-GCP-0047",
  "apiVersion": 2,
  "version": 1,
  "title": "Users should not be granted service account access at the project level",
  "description": "Users with service account access at project level can impersonate any service account. Instead, they should be given access to particular service accounts as required.",
  "custom": {
    "severity": "MEDIUM",
    "possibleImpact": "Privilege escalation, impersonation of any/all services",
    "references": [
      {
        "title": "title",
        "url": "https://cloud.google.com/iam/docs/impersonating-service-accounts"
      }
    ],
    "externalToolIds": {
      "cfsec": [],
      "cspm": [],
      "tfsec": [
        "google-iam-no-project-level-service-account-impersonation"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/aws/efs/enable-at-rest-encryption/metadata.json
{
  "id": "AVD-AWS-0037",
  "apiVersion": 2,
  "version": 1,
  "title": "EFS Encryption has not been enabled",
  "description": "If your organization is subject to corporate or regulatory policies that require encryption of data and metadata at rest, we recommend creating a file system that is encrypted at rest, and mounting your file system using encryption of data in transit.",
  "custom": {
    "severity": "HIGH",
    "possibleImpact": "Data can be read from the EFS if compromised",
    "references": [
      {
        "title": "title",
        "url": "https://docs.aws.amazon.com/efs/latest/ug/encryption.html"
      }
    ],
    "externalToolIds": {
      "cfsec": [
        "aws-efs-enable-at-rest-encryption"
      ],
      "cspm": [
        {
          "id": -1,
          "name": "TODO-CSPM-PLUGIN-NAME"
        }
      ],
      "tfsec": [
        "aws-efs-enable-at-rest-encryption"
      ]
    }
  }
}
