=== aquasecurity/cloud-metadata/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "apiVersion": {
            "type": "integer"
        },
        "version": {
            "type": "integer"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "description_file_path": {
            "type": "string"
        },
        "custom": {
            "type": "object",
            "properties": {
                "severity": {
                    "type": "string"
                },
                "possibleImpact": {
                    "type": "string"
                },
                "remediations": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string"
                                },
                                "remediation_path": {
                                    "type": "string"
                                },
                                "remediation_type": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "title",
                                "remediation_path",
                                "remediation_type"
                            ]
                        }
                    ]
                },
                "references": {
                    "type": "array",
                    "items": [
                        {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string"
                                },
                                "url": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "title",
                                "url"
                            ]
                        }
                    ]
                },
                "externalToolIds": {
                    "type": "object",
                    "properties": {
                        "cfsec": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        },
                        "cspm": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "integer"
                                        },
                                        "name": {
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "id",
                                        "name"
                                    ]
                                }
                            ]
                        },
                        "tfsec": {
                            "type": "array",
                            "items": [
                                {
                                    "type": "string"
                                }
                            ]
                        }
                    }
                }
            },
            "required": [
                "severity",
                "possibleImpact",
                "references",
                "externalToolIds"
            ]
        }
    },
    "required": [
        "id",
        "apiVersion",
        "version",
        "title",
        "description",
        "custom"
    ]
}

=== aquasecurity/cloud-metadata/aws/api-gateway/enable-access-logging/metadata.json
{
    "id": "AVD-AWS-0001",
    "apiVersion": 2,
    "version": 1,
    "title": "API Gateway stages for V1 and V2 should have access logging enabled",
    "description": "API Gateway stages should have access log settings block configured to track all access to a particular stage. This should be applied to both v1 and v2 gateway stages.",
    "custom": {
        "severity": "MEDIUM",
        "possibleImpact": "Logging provides vital information about access and usage",
        "references": [
            {
                "title": "Setting up CloudWatch logging for a REST API in API Gateway",
                "url": "https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html"
            }
        ],
        "externalToolIds": {
            "cfsec": [
                "aws-api-gateway-enable-access-logging"
            ],
            "cspm": [
                {
                    "id": 935,
                    "name": "apigateway/apigatewayCloudwatchLogs"
                }
            ],
            "tfsec": [
                "aws-api-gateway-enable-access-logging"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/azure/appservice/enable-http2/metadata.json
{
  "id": "AVD-AZU-0003",
  "apiVersion": 2,
  "version": 1,
  "title": "Web App uses the latest HTTP version",
  "description": "Use the latest version of HTTP to ensure you are benefiting from security fixes",
  "custom": {
    "severity": "LOW",
    "possibleImpact": "Outdated versions of HTTP has security vulnerabilities",
    "references": [],
    "externalToolIds": {
      "cfsec": [],
      "cspm": [
        {
          "id": 421,
          "name": "appservice/http20Enabled"
        }
      ],
      "tfsec": [
        "azure-appservice-enable-http2"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/aws/elastic-search/enable-domain-logging/metadata.json
{
  "id": "AVD-AWS-0042",
  "apiVersion": 2,
  "version": 1,
  "title": "Domain logging should be enabled for Elastic Search domains",
  "description": "Amazon ES exposes four Elasticsearch logs through Amazon CloudWatch Logs: error logs, search slow logs, index slow logs, and audit logs. \n\nSearch slow logs, index slow logs, and error logs are useful for troubleshooting performance and stability issues. \n\nAudit logs track user activity for compliance purposes. \n\nAll the logs are disabled by default.",
  "custom": {
    "severity": "MEDIUM",
    "possibleImpact": "Logging provides vital information about access and usage",
    "references": [
      {
        "title": "title",
        "url": "https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createdomain-configure-slow-logs.html"
      }
    ],
    "externalToolIds": {
      "cfsec": [
        "aws-elastic-search-enable-domain-logging"
      ],
      "cspm": [
        {
          "id": 661,
          "name": "es/esLoggingEnabled"
        }
      ],
      "tfsec": [
        "aws-elastic-search-enable-domain-logging"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/digitalocean/loadbalancing/enforce-https/metadata.json
{
  "id": "AVD-DIG-0004",
  "apiVersion": 2,
  "version": 1,
  "title": "The load balancer forwarding rule is using an insecure protocol as an entrypoint",
  "description": "Plain HTTP is unencrypted and human-readable. This means that if a malicious actor was to eavesdrop on your connection, they would be able to see all of your data flowing back and forth.\n\nYou should use HTTPS, which is HTTP over an encrypted (TLS) connection, meaning eavesdroppers cannot read your traffic.",
  "custom": {
    "severity": "CRITICAL",
    "possibleImpact": "Your inbound traffic is not protected",
    "references": [
      {
        "title": "title",
        "url": "https://docs.digitalocean.com/products/networking/load-balancers/"
      }
    ],
    "externalToolIds": {
      "cfsec": [],
      "cspm": [
        {
          "id": -1,
          "name": "TODO-CSPM-PLUGIN-NAME"
        }
      ],
      "tfsec": [
        "digitalocean-loadbalancing-enforce-https"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/aws/iam/block-kms-policy-wildcard/metadata.json
{
  "id": "AVD-AWS-0055",
  "apiVersion": 2,
  "version": 1,
  "title": "IAM customer managed policies should not allow decryption actions on all KMS keys",
  "description": "IAM policies define which actions an identity (user, group, or role) can perform on which resources. Following security best practices, AWS recommends that you allow least privilege. In other words, you should grant to identities only the kms:Decrypt or kms:ReEncryptFrom permissions and only for the keys that are required to perform a task.",
  "custom": {
    "severity": "HIGH",
    "possibleImpact": "Identities may be able to decrypt data which they should not have access to",
    "references": [
      {
        "title": "title",
        "url": "https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-kms-1"
      }
    ],
    "externalToolIds": {
      "cfsec": [
        "aws-iam-block-kms-policy-wildcard"
      ],
      "cspm": [],
      "tfsec": [
        "aws-iam-block-kms-policy-wildcard"
      ]
    }
  }
}

=== aquasecurity/cloud-metadata/google/compute/disk-encryption-customer-keys/metadata.json
{
    "id": "AVD-GCP-0003",
    "apiVersion": 2,
    "version": 1,
    "title": "Encrypted compute disk with unmanaged keys.",
    "description": "By default, Compute Engine encrypts all data at rest. Compute Engine handles and manages this encryption for you without any additional actions on your part.\n\nIf the disk_encryption_key block is included in the resource declaration then it *must* include a raw_key or kms_key_self_link.",
    "custom": {
        "severity": "HIGH",
        "possibleImpact": "Encryption of disk using unmanaged keys.",
        "references": [
            {
                "title": "Encrypt disks with customer-supplied encryption keys",
                "url": "https://cloud.google.com/compute/docs/disks/customer-supplied-encryption"
            }
        ],
        "externalToolIds": {
            "cfsec": [],
            "cspm": [
                {
                    "id": 643,
                    "name": "compute/csekEncryptionEnabled"
                }
            ],
            "tfsec": [
                "google-compute-disk-encryption-customer-keys"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/azure/network/no-public-ingress/metadata.json
{
    "id": "AVD-AZU-0041",
    "apiVersion": 2,
    "version": 1,
    "title": "An inbound network security rule allows traffic from /0.",
    "description": "Network security rules should not use very broad subnets.\n\nWhere possible, segments should be broken into smaller subnets.",
    "custom": {
        "severity": "CRITICAL",
        "possibleImpact": "The port is exposed for ingress from the internet",
        "references": [
            {
                "title": "Best practices for network security",
                "url": "https://docs.microsoft.com/en-us/azure/security/fundamentals/network-best-practices"
            }
        ],
        "externalToolIds": {
            "cfsec": [],
            "cspm": [],
            "tfsec": [
                "azure-network-no-public-ingress"
            ]
        }
    }
}

=== aquasecurity/cloud-metadata/google/compute/no-default-service-account/metadata.json
{
  "id": "AVD-GCP-0007",
  "apiVersion": 2,
  "version": 1,
  "title": "Instances should not use the default service account",
  "description": "The default service account has full project access. Instances should instead be assigned the minimal access they need.",
  "custom": {
    "severity": "CRITICAL",
    "possibleImpact": "Instance has full access to the project",
    "references": [],
    "externalToolIds": {
      "cfsec": [],
      "cspm": [
        {
          "id": -1,
          "name": "TODO-CSPM-PLUGIN-NAME"
        }
      ],
      "tfsec": [
        "google-compute-no-default-service-account"
      ]
    }
  }
}
